# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: 修复
      labels:
        - fix
        - bug
    - title: 功能
      labels:
        - feat
        - enhancement
    - title: 维护
      labels:
        - chore
        - deploy
    - title: 其他更新
      labels:
        - "*"
